name: overlay_plus
description: "A new Flutter package project."
version: 0.0.1+4
homepage: https://1080motion.com
publish_to: "none" # DO NOT PUBLISH TO PUB.DEV

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # ... Ten eightee packages ...
  tem_lints: ^0.0.1+3

flutter:
  uses-material-design: true
